---
:global:
  build:
    matrix:
      - GOOS: linux
        GOARCH: amd64
.travis.yml:
  env:
    global:
      - ORG_PATH=/home/travis/gopath/src/github.com/intelsdi-x
      - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/${TRAVIS_REPO_SLUG}
    matrix:
      - TEST_TYPE=small
      - TEST_TYPE=medium
  deploy:
    access_key_id: AKIAINMB43VSSPFZISAA
    secret_access_key:
      secure: YvbymtPIqf/VvjBGlZNNTr1bQ5BWvBETEmTq9xprCzfYz5WvNKS7VYDrLmN8ZKF9SJAjpad0a93TCSkR/78Z/awMIKscCWODsYyYfSDkzN+uIqFhFKse6YnaU3795qmt8gZAf4guNQthOYGtlLEwsl3O0vlmesCXAR6Dwi1IGN+t9BUnCgM7OmcTcNpRHoedwIgY0M7c+JbFJtx1vP1+Tc1JL5w8q7PaMdsTPlbhW7w+i+zrjYpuskxcc+A6VoYB+lKf+wrX/uHM8pHSPYJOS5Kp0m8khbLED820geoZ79knUTcxMxrqPsXXk9/QqSK0dR0M5Jey8j2H9jUfAEgN/4nAftSVTJitVnDlIU2blx6Fly/nNkiZHqXw9T87Sdl9ZF/sTOwDJaPnsDbh9gwf9QXeWwi7k+qFBu1IhYtoV6K/ynRVHWBl1SaHOBD3GcaA4rLYQM1Bk2vC4Cs75IA5o1wFsg9OFkPAjwawasaXKypQpP/Zk0hfDS3HsX3fDObHOelH1i5ajqxltZEg4OJCMkKyRfjAHtulxtRTLzxMm+Cj/flBRvr8UvhUEeUuCMDXszatbwKMLLFGY0hgKDqpjCliSnRqnHBfbDhc1t5So02x2ngx4Uw2tzySvWjDCBGRDRNeI+rE78VCD4EQWZCJRH10+Eqdxe209aNLMI/dli0=
    api_key:
      secure: r6hwOMU7YUxuWLoBFjZJ/LeNr469XmpCmcUVh8dHYYjLK4XrAQZej+kiaqhJh289ZeCdlwDTKZN/pcd+miiOBS50c/wjmSQKyhCY29U6olkQf2dPbpvn3ICoSgfD09BumXmaGWEc9jo+VVYJBp/m7Nb1bpka4zwj7XlSn7k0z820kKHlokH4Fe3jKZWoWNSRrJfU5fiOqzq6B1rXa+Upjt8QButZd68BUuSL/1PONtUoF691+ao6+cqBYDsWl5cViEFsaX/wGNuBVWHF4unJl4dPaJhaTv3STAPbGZdaxfm28WCJ9ERllTCEnHdU2nSaXNLMeba4XVp1kXsy63nyKSq3WVu/+uD6qPaTqYXIxGhqkkb1Htxnz6y+bxgniYU9wGAQdHbyjC1/Dhj+++w+MOHNlSOcxfZyTKLdozXa96jXOwIE4XU1NXN3OvYiIaCW0Tb1n9kAaTn92jMycrlnAXTPLVE+QwJ/WXV5ureqmzO9llr/fjoxHGo878o2oz3yn+LT5Kg3hmkZBn60JlhuM72CRN9D5zEhIL/5C+rDFlMIESdppT3g/9nH/MsQSKZW/Yx06TZnxlhQprvQE4EmOX36bGfdKodpX4XZh59U7YPjsvmT0AEb+rs2zbTjEVbbkq98ECLWbGvQ+dpw3hPwrI97vj/fXG7sjf5N99ogb+Y=
